name: validate-runbook-adr-links

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - "docs/20-governance/runbooks/**"
      - "docs/20-governance/design/adr/**"
      - ".github/workflows/validate-runbook-adr-links.yml"

jobs:
  call-validate-runbook-adr-links:
    uses: yai-labs/yai-infra/.github/workflows/reusable-validate-runbook-adr-links.yml@717ad404eb98e889b72201bd0bc65e3710441449
